server:
  port: 8073

spring:
  application:
    name: "transaction-microservice"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    username: "stephenfreed"
    password: "password"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://aline-mysql:3306/alinedb"
    initialization-mode: always

app:
  admin-portal: "${PORTAL_ADMIN}"
  member-dashboard: "${PORTAL_DASHBOARD}"
  landing-portal: "${PORTAL_LANDING}"
  sms:
    enable: true
  email:
    from: "no-reply@alinefinancial.com"
    enable: true
  aws:
    email:
      template-bucket-name: "aline-email-templates"
    credentials:
      access-key-id: "${APP_USER_ACCESS_KEY}"
      secret-access-key: "${APP_USER_SECRET_KEY}"
  security:
    secret-key: "?D(G-KaPdSgVkYp3s6v9y$B&E)H@MbQe"
    jwt:
      secret-key: "?D(G-KaPdSgVkYp3s6v9y$B&E)H@MbQe"



